Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/ubuntu-24.04"

    vm1.vm.network "public_network"

    vm1.vm.synced_folder "./shared_vm1", "/var/www/shared"

    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt install -y nginx
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-24.04"

    vm2.vm.network "private_network", ip: "192.168.56.10"

    vm2.vm.synced_folder "./shared_vm2", "/opt/shared"

    vm2.vm.provision "shell", path: "provision_vm2.sh"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "bento/ubuntu-24.04"

    vm3.vm.network "public_network",
      ip: "192.168.1.200",
      bridge: "Wi-Fi"

    vm3.vm.synced_folder "./shared_vm3", "/data"
  end

end
